### ISSUE TITLE
Playing sound in Python

### ISSUE THREAD

**Issue by panmari** [zombiecalypse/SAM#1]
Nothing really works... i tried
- pygame - no errors, but only gives short distortion sound
- pyglet - says: [mp3 @ 0x24c4480] max_analyze_duration reached, only plays half a sec of the file
- tkSnack - Doesn't do anything, not even error

This sucks -.-

Any ideas?

**Comment by zombiecalypse** [comment]
funktioniert pyogg? also eben, ich vermute, dass .ogg dateien besser
unterstützt werden (und besser komprimiert sind)...

On 27 December 2011 21:49, panmari <
reply@reply.github.com

**Comment by panmari** [comment]
for now, we'll use pygame which can handle .ogg just fine. Someone has to convert the stuff to .ogg, though...
